// Generated by sure-factor from catalog/form.yaml.
// Component: form — DOM renderer, no framework, no dependencies.
//
// The form is driven by a FormSpec supplied by the server, so one module
// renders every entity. Field names come from the catalog-matched columns of
// the schema this was generated against.

export interface FieldHints {
  placeholder?: string
  help?: string
  error?: { required?: string; format?: string; tooShort?: string; tooLong?: string }
}

export interface FieldSpec {
  name: string
  label: string
  help: string
  required: boolean
  control: 'text' | 'password' | 'select' | 'textarea' | 'hidden'
  type: string
  options?: string[]
  readOnly?: boolean
  secret?: boolean
  json?: boolean
  validation: { regex?: string | null; minLength?: number | null; maxLength?: number | null }
  hints: FieldHints
  sanitize: string[]
  source: { table: string; column: string } | null
}

export interface FormSpec {
  id: string
  title: string
  fields: FieldSpec[]
}

/** Minimal element factory. Children may be nodes, strings, or nested arrays. */
export function h<K extends keyof HTMLElementTagNameMap>(
  tag: K,
  props?: Record<string, unknown> | null,
  ...children: Array<Node | string | null | undefined | Array<Node | string | null | undefined>>
): HTMLElementTagNameMap[K] {
  const el = document.createElement(tag)
  if (props) {
    for (const [key, value] of Object.entries(props)) {
      if (value === null || value === undefined || value === false) continue
      if (key === 'class') el.className = String(value)
      else if (key.startsWith('on') && typeof value === 'function') {
        el.addEventListener(key.slice(2).toLowerCase(), value as EventListener)
      } else if (value === true) el.setAttribute(key, '')
      else el.setAttribute(key, String(value))
    }
  }
  const add = (child: Node | string | null | undefined | Array<Node | string | null | undefined>): void => {
    if (child === null || child === undefined) return
    if (Array.isArray(child)) {
      for (const c of child) add(c)
      return
    }
    el.appendChild(typeof child === 'string' ? document.createTextNode(child) : child)
  }
  for (const child of children) add(child)
  return el
}

function fieldId(name: string): string {
  return `field-${name}`
}

/** One labelled control plus its help and error text. */
export function renderField(
  field: FieldSpec,
  value: string,
  error: string | undefined,
  busy: boolean,
  onChange: (name: string, value: string) => void,
): HTMLElement {
  const id = fieldId(field.name)
  const describedBy = error ? `${id}-error` : field.help ? `${id}-help` : undefined

  const common: Record<string, unknown> = {
    id,
    name: field.name,
    value: field.control === 'select' ? value || (field.options?.[0] ?? '') : value,
    required: field.required,
    disabled: field.readOnly === true || busy,
    readOnly: field.readOnly === true,
    autocomplete: field.control === 'password' ? 'new-password' : 'off',
    'aria-invalid': error ? 'true' : 'false',
    'aria-describedby': describedBy,
    placeholder: field.hints?.placeholder ?? '',
    minlength: field.validation?.minLength ?? undefined,
    maxlength: field.control === 'textarea' ? undefined : (field.validation?.maxLength ?? undefined),
    oninput: (e: Event) => onChange(field.name, (e.target as HTMLInputElement).value),
  }

  let control: HTMLElement
  if (field.control === 'select') {
    const select = h('select', common)
    if (!field.required) {
      const blank = h('option', { value: '' }, '\u2014')
      select.appendChild(blank)
    }
    for (const opt of field.options ?? []) {
      select.appendChild(h('option', { value: opt }, opt))
    }
    control = select
  } else if (field.control === 'textarea') {
    control = h('textarea', { ...common, rows: 5, spellcheck: 'false' })
  } else {
    const type = field.control === 'password' ? 'password' : (field.type === 'email' ? 'email' : 'text')
    control = h('input', { ...common, type })
  }

  const label = h('label', { class: "sure-form__label", for: id }, field.label)
  if (field.required) label.appendChild(h('span', { 'aria-hidden': 'true' }, ' *'))

  const parts: HTMLElement[] = [label, control]
  if (field.help || field.hints?.help) {
    parts.push(
      h('div', { class: "sure-form__help", id: `${id}-help` },
        [field.help, field.hints?.help].filter(Boolean).join(' \u2014 ')),
    )
  }
  if (error) {
    parts.push(h('div', { class: "sure-form__error", id: `${id}-error`, role: 'alert' }, error))
  }
  return h('div', { class: "sure-form__field" }, ...parts)
}

export interface FormOptions {
  values?: Record<string, string>
  errors?: Record<string, string>
  busy?: boolean
  submitLabel?: string
  onChange: (name: string, value: string) => void
  onSubmit: (values: Record<string, string>) => void
  onCancel?: () => void
  /** Called instead of onSubmit when the values fail validation. */
  onInvalid?: (errors: Record<string, string>) => void
  /** Set false to submit without validating — e.g. for a draft save. */
  validate?: boolean
}

/**
 * Validate a form's values against its spec.
 *
 * The catalog carries the rules (required, regex, min/max length, JSON), and
 * every consumer had been re-implementing this — the management console kept
 * its own copy in formspec.ts. Rules live in the generated module so they
 * cannot drift from the fields they describe.
 *
 * Returns field name → message; an empty object means valid. Never throws: a
 * malformed regex in the catalog is treated as "no constraint" rather than
 * failing the form.
 */
export function validateForm(
  spec: FormSpec,
  values: Record<string, string>,
): Record<string, string> {
  const errors: Record<string, string> = {}
  for (const field of spec.fields) {
    if (field.control === 'hidden') continue
    const value = values[field.name] ?? ''
    const v = field.validation ?? {}

    if (field.required && value.trim() === '') {
      errors[field.name] = field.hints?.error?.required ?? `${field.label} is required`
      continue
    }
    if (value === '') continue

    if (field.json) {
      try {
        JSON.parse(value)
      } catch {
        errors[field.name] = 'must be valid JSON'
        continue
      }
    }

    if (v.regex) {
      let ok = true
      try {
        ok = new RegExp(v.regex, 'u').test(value)
      } catch {
        ok = true
      }
      if (!ok) {
        errors[field.name] = field.hints?.error?.format ?? `${field.label} has an invalid format`
        continue
      }
    }

    if (v.minLength != null && value.length < v.minLength) {
      errors[field.name] =
        field.hints?.error?.tooShort ?? `${field.label} must be at least ${v.minLength} characters`
      continue
    }
    if (v.maxLength != null && field.control !== 'textarea' && value.length > v.maxLength) {
      errors[field.name] =
        field.hints?.error?.tooLong ?? `${field.label} must be at most ${v.maxLength} characters`
    }
  }
  return errors
}

/** Sanitise values using each field's catalog sanitisation steps. */
export function sanitizeForm(
  spec: FormSpec,
  values: Record<string, string>,
): Record<string, string> {
  const out: Record<string, string> = {}
  for (const field of spec.fields) {
    let value = values[field.name] ?? ''
    if (field.control !== 'hidden' && field.control !== 'textarea' && v_max(field)) {
      value = value.slice(0, v_max(field)!)
    }
    out[field.name] = value.trim()
  }
  return out
}

function v_max(field: { validation?: { maxLength?: number | null } }): number | null {
  const n = field.validation?.maxLength
  return typeof n === 'number' && n > 0 ? n : null
}

/** Render a FormSpec into a form element wired to the supplied callbacks. */
export function renderForm(spec: FormSpec, options: FormOptions): HTMLFormElement {
  const values = options.values ?? {}
  const errors = options.errors ?? {}
  const busy = options.busy ?? false

  const visible = spec.fields.filter((f) => f.control !== 'hidden')
  const form = h('form', {
    class: "sure-form",
    'aria-label': spec.title,
    novalidate: true,
    onsubmit: (e: Event) => {
      e.preventDefault()
      if (busy) return
      if (options.validate === false) {
        options.onSubmit(values)
        return
      }
      // Validate before handing anything over. The rules come from the catalog
      // via the spec, so a malformed value never leaves the browser.
      const found = validateForm(spec, values)
      if (Object.keys(found).length === 0) {
        options.onSubmit(sanitizeForm(spec, values))
        return
      }
      // Tell the caller what is wrong; it owns the render loop and decides how
      // to show it.
      if (options.onInvalid) options.onInvalid(found)
      else options.onSubmit(values)
    },
  })

  form.appendChild(h('h2', { class: "sure-form__title" }, spec.title))
  for (const field of visible) {
    form.appendChild(renderField(field, values[field.name] ?? '', errors[field.name], busy, options.onChange))
  }

  const actions = h('div', { class: "sure-form__actions" })
  actions.appendChild(h('button', { class: "btn-primary", type: 'submit', disabled: busy },
    options.submitLabel ?? 'Save'))
  if (options.onCancel) {
    actions.appendChild(h('button', {
      class: "btn-secondary",
      type: 'button',
      disabled: busy,
      onclick: () => options.onCancel?.(),
    }, 'Cancel'))
  }
  form.appendChild(actions)
  return form
}

/** The fields this module was generated for, for a server to fill a spec from. */
export const GENERATED_FIELDS: FieldSpec[] = [
  {
    "name": "id",
    "label": "Id",
    "control": "text",
    "type": "text",
    "required": false,
    "readOnly": true,
    "secret": false,
    "json": false,
    "validation": {
      "regex": null,
      "minLength": null,
      "maxLength": null
    },
    "sanitize": [
      "trim",
      "collapseWhitespace",
      "normalize: NFKC",
      "stripControl",
      "slice(0, maxLength)"
    ],
    "help": "",
    "hints": {
      "placeholder": "Enter text...",
      "help": "",
      "error": {
        "format": "",
        "required": "This field is required"
      }
    },
    "source": {
      "table": "subscribers",
      "column": "id"
    }
  },
  {
    "name": "email",
    "label": "Email",
    "control": "text",
    "type": "email",
    "required": true,
    "readOnly": false,
    "secret": false,
    "json": false,
    "validation": {
      "regex": "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$",
      "minLength": null,
      "maxLength": 254
    },
    "sanitize": [
      "trim",
      "lowercase",
      "normalize: NFKC",
      "stripControl",
      "slice(0, 254)"
    ],
    "help": "Email address",
    "hints": {
      "placeholder": "user@example.com",
      "help": "Email address",
      "error": {
        "format": "Invalid email address",
        "required": "Email is required"
      }
    },
    "source": {
      "table": "subscribers",
      "column": "email"
    }
  },
  {
    "name": "display_name",
    "label": "Display name",
    "control": "text",
    "type": "full-name",
    "required": true,
    "readOnly": false,
    "secret": false,
    "json": false,
    "validation": {
      "regex": null,
      "minLength": null,
      "maxLength": 100
    },
    "sanitize": [
      "trim",
      "collapseWhitespace",
      "normalize: NFKC",
      "stripControl",
      "slice(0, 100)"
    ],
    "help": "Full legal name",
    "hints": {
      "placeholder": "Jane Doe",
      "help": "Full legal name",
      "error": {
        "format": "Name must be 1-100 characters",
        "required": "Name is required"
      }
    },
    "source": {
      "table": "subscribers",
      "column": "display_name"
    }
  },
  {
    "name": "plan",
    "label": "Plan",
    "control": "text",
    "type": "text",
    "required": true,
    "readOnly": false,
    "secret": false,
    "json": false,
    "validation": {
      "regex": null,
      "minLength": null,
      "maxLength": null
    },
    "sanitize": [
      "trim",
      "collapseWhitespace",
      "normalize: NFKC",
      "stripControl",
      "slice(0, maxLength)"
    ],
    "help": "",
    "hints": {
      "placeholder": "Enter text...",
      "help": "",
      "error": {
        "format": "",
        "required": "This field is required"
      }
    },
    "source": {
      "table": "subscribers",
      "column": "plan"
    }
  },
  {
    "name": "signup_date",
    "label": "Signup date",
    "control": "text",
    "type": "date-us",
    "required": true,
    "readOnly": false,
    "secret": false,
    "json": false,
    "validation": {
      "regex": "^\\d{2}/\\d{2}/\\d{4}$",
      "minLength": null,
      "maxLength": 10
    },
    "sanitize": [
      "trim",
      "normalize: NFKC",
      "slice(0, 10)"
    ],
    "help": "Date in MM/DD/YYYY format",
    "hints": {
      "placeholder": "07/24/2026",
      "help": "Date in MM/DD/YYYY format",
      "error": {
        "format": "Must be a valid date in MM/DD/YYYY format",
        "required": "Date is required"
      }
    },
    "source": {
      "table": "subscribers",
      "column": "signup_date"
    }
  },
  {
    "name": "notes",
    "label": "Notes",
    "control": "text",
    "type": "text",
    "required": false,
    "readOnly": false,
    "secret": false,
    "json": false,
    "validation": {
      "regex": null,
      "minLength": null,
      "maxLength": null
    },
    "sanitize": [
      "trim",
      "collapseWhitespace",
      "normalize: NFKC",
      "stripControl",
      "slice(0, maxLength)"
    ],
    "help": "",
    "hints": {
      "placeholder": "Enter text...",
      "help": "",
      "error": {
        "format": "",
        "required": "This field is required"
      }
    },
    "source": {
      "table": "subscribers",
      "column": "notes"
    }
  },
  {
    "name": "invitations_id",
    "label": "Id",
    "control": "text",
    "type": "text",
    "required": false,
    "readOnly": true,
    "secret": false,
    "json": false,
    "validation": {
      "regex": null,
      "minLength": null,
      "maxLength": null
    },
    "sanitize": [
      "trim",
      "collapseWhitespace",
      "normalize: NFKC",
      "stripControl",
      "slice(0, maxLength)"
    ],
    "help": "",
    "hints": {
      "placeholder": "Enter text...",
      "help": "",
      "error": {
        "format": "",
        "required": "This field is required"
      }
    },
    "source": {
      "table": "invitations",
      "column": "id"
    }
  },
  {
    "name": "invitations_email",
    "label": "Email",
    "control": "text",
    "type": "email",
    "required": true,
    "readOnly": false,
    "secret": false,
    "json": false,
    "validation": {
      "regex": "^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$",
      "minLength": null,
      "maxLength": 254
    },
    "sanitize": [
      "trim",
      "lowercase",
      "normalize: NFKC",
      "stripControl",
      "slice(0, 254)"
    ],
    "help": "Email address",
    "hints": {
      "placeholder": "user@example.com",
      "help": "Email address",
      "error": {
        "format": "Invalid email address",
        "required": "Email is required"
      }
    },
    "source": {
      "table": "invitations",
      "column": "email"
    }
  },
  {
    "name": "invited_by",
    "label": "Invited by",
    "control": "text",
    "type": "text",
    "required": true,
    "readOnly": false,
    "secret": false,
    "json": false,
    "validation": {
      "regex": null,
      "minLength": null,
      "maxLength": null
    },
    "sanitize": [
      "trim",
      "collapseWhitespace",
      "normalize: NFKC",
      "stripControl",
      "slice(0, maxLength)"
    ],
    "help": "",
    "hints": {
      "placeholder": "Enter text...",
      "help": "",
      "error": {
        "format": "",
        "required": "This field is required"
      }
    },
    "source": {
      "table": "invitations",
      "column": "invited_by"
    }
  },
  {
    "name": "created_at",
    "label": "Created at",
    "control": "text",
    "type": "text",
    "required": false,
    "readOnly": false,
    "secret": false,
    "json": false,
    "validation": {
      "regex": null,
      "minLength": null,
      "maxLength": null
    },
    "sanitize": [
      "trim",
      "collapseWhitespace",
      "normalize: NFKC",
      "stripControl",
      "slice(0, maxLength)"
    ],
    "help": "",
    "hints": {
      "placeholder": "Enter text...",
      "help": "",
      "error": {
        "format": "",
        "required": "This field is required"
      }
    },
    "source": {
      "table": "invitations",
      "column": "created_at"
    }
  }
]

export const CSS_CLASSES = {
  "form": "sure-form",
  "field": "sure-form__field",
  "input": "sure-form__input",
  "error": "sure-form__error",
  "help": "sure-form__help",
  "label": "sure-form__label",
  "title": "sure-form__title",
  "actions": "sure-form__actions",
  "submit": "btn-primary",
  "cancel": "btn-secondary"
} as const

export default renderForm
