// Step 2 — turn the generated component into something you can look at.
//
// Sure-factor wrote form.ts. This file copies it next to a stylesheet from
// sure-ui and produces index.html, so the result opens in a browser with no
// server, no build step and no framework.
//
//     node scripts/build.mjs
//
// There is nothing to install and nothing to configure. The output is
// self-contained: open it and the form works, including validation.

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";
import { themes } from "@shing.wong/sure-ui";

const here = new URL("../", import.meta.url);
const dist = new URL("dist/", here);
mkdirSync(dist, { recursive: true });

// 1. The generated component is TypeScript; esbuild turns it into something a
//    browser can load directly. No bundler configuration, no framework.
const result = await build({
  entryPoints: [fileURLToPath(new URL("form.ts", here))],
  bundle: true,
  outfile: fileURLToPath(new URL("form.js", dist)),
  format: "esm",
  platform: "browser",
  target: ["chrome110", "firefox115", "safari16"],
  minify: true,
  legalComments: "none",
  logLevel: "error",
});
if (result.errors.length > 0) process.exit(1);

// 2. Pick a theme and write its CSS. sure-ui ships plain CSS strings, so
//    this works with no build tooling at all — pick a name, get styles.
const themeName = process.env.THEME ?? "nord";
const css = themes[themeName];
if (!css) throw new Error(`Unknown theme "${themeName}". Try: ${Object.keys(themes).join(", ")}`);
writeFileSync(fileURLToPath(new URL("theme.css", dist)), css);

// 3. A page that uses it.
const page = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Subscriber form — generated by sure-factor</title>
  <link rel="stylesheet" href="theme.css">
  <style>
    body { margin: 0; padding: 2rem; font-family: system-ui, sans-serif; background: var(--bg); color: var(--text); }
    main { max-width: 34rem; margin: 0 auto; }
    .note { font-size: 0.875rem; opacity: 0.7; margin-top: 1.5rem; }
    #result { margin-top: 1.5rem; }
    pre { background: rgba(127,127,127,0.12); padding: 0.75rem; border-radius: 6px; overflow-x: auto; font-size: 0.8125rem; }
  </style>
</head>
<body>
  <main>
    <div id="form"></div>
    <pre id="result" hidden></pre>
    <p class="note">
      Every field, label, validation rule and CSS class below came from
      schema.sql. Nothing here was written by hand.
    </p>
  </main>
  <script type="module">
    import { renderForm, GENERATED_FIELDS } from './form.js';

    // The server would send this. Here we build it from the same generated
    // field list so the example runs on its own.
    const spec = {
      id: 'subscribers',
      title: 'New subscriber',
      // Each field records which table and column it came from, so select
      // one table's fields rather than guessing from the name.
      fields: GENERATED_FIELDS.filter(f => f.source?.table === 'subscribers'),
    };

    let values = {};
    let errors = {};

    function draw() {
      const form = renderForm(spec, {
        values,
        errors,
        // Validation lives in the generated component. It calls this with the
        // messages, and we redraw to show them.
        onInvalid(found) {
          errors = found;
          draw();
        },
        submitLabel: 'Subscribe',
        onChange(name, value) {
          values = { ...values, [name]: value };
          draw();
        },
        onSubmit(v) {
          // Real validation lives on the server. This just shows the payload
          // the generated form produced.
          const out = document.getElementById('result');
          out.hidden = false;
          out.textContent = JSON.stringify(v, null, 2);
        },
        onCancel() {
          values = {};
          document.getElementById('result').hidden = true;
          draw();
        },
      });
      document.getElementById('form').replaceChildren(form);
    }

    draw();
  </script>
</body>
</html>
`;
writeFileSync(fileURLToPath(new URL("index.html", dist)), page);

console.log(`Wrote dist/index.html, dist/form.js and dist/theme.css (theme: ${themeName})`);
console.log("Open dist/index.html in a browser, or run: npm start");

/**
 * The generated module is TypeScript. Strip the two type annotations it uses
 * so the browser can load it directly — no bundler in this example.
 */
function tsToJs(source) {
  return source
    .replace(/^\s*(export\s+)?interface\s+\w+\s*\{[\s\S]*?^\}\s*$/gm, "")
    .replace(/^export type .*$/gm, "")
    .replace(/<K extends keyof HTMLElementTagNameMap>/g, "")
    .replace(/\)\s*:\s*HTMLElementTagNameMap\[K\]\s*\{/g, ") {")
    .replace(/\)\s*:\s*HTMLElement\s*\{/g, ") {");
}